### ISSUE TITLE
GetJobListingById returns only the first child of employer.joblistings

### ISSUE THREAD

**Issue by vincentlemstra** [vincentlemstra/VacIT#1]
https://github.com/vincentlemstra/VacIT/blob/1ce317f5e0ae66d424867e0bfcda53607867a3c0/VacIT/ApiControllers/JobListingsController.cs#L38-L51

@JeroenHeemskerk 
Als ik JobListing ophaal met bijbehorende Employer, krijg ik vervolgens alleen het eerste child van dit Employer JobListing. Ik wil hier alle children ophalen zodat ik op de detail pagina alle JobListings kan tonen van de Employer. 

Issues die ik zelf heb onderzocht maar niet uit kwam:
1. FirstOrDefault() returns de eerste match
2. Wanneer de Employer relatie mee wordt geladen, komt de data in een loop: Employer heeft weer JobListings -> JobListings hebben weer employers. Na onderzoek heb ik in program.cs de volgende regel toegevoegd: `builder.Services.AddControllers().AddJsonOptions(x =>
                x.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles);`
Dit heeft het probleem niet opgelost.

**Comment by JeroenHeemskerk** [comment]
Volgens mij moet je hem dan vertellen om ook alle joblistings van deze employer op te halen
```c-sharp
var jobListing = _context.JobListings.Include(n => n.Employer).Include(e => e.JobListings).FirstOrDefault(n => n.Id == id); 
```

Je kan echter niet het employer object met alle joblistings teruggeven, omdat je dan idd in een look komt.
Wat je kan doen is een nieuw object maken met daarin de JobListing, en een list van joblistings
```c-sharp
    return new JobListingInclusiveAllJobs() { JobListing = Joblisting, Other = JobListing.Employer.Joblistings };
```
